[package]
name = "rust_decoding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.9.3"
base64 = "0.13.0"
hex = "0.3.1"
